package kh.java.func;

import java.util.InputMismatchException;
import java.util.Scanner;

public class ExceptionTest {
	private Scanner sc;
	
	public ExceptionTest() {
		super();
		sc = new Scanner(System.in);
	}

	public void exceptionTest1() {
		while(true) {
			System.out.println("정수를 입력 하세요 : ");
			int num =0;
			try {
				num = sc.nextInt();
			}catch(InputMismatchException e) {
				System.out.println("에러 발생!");
			}
			System.out.println("결과 : "+num);
			if(num == 0) {
				break;
			}
		}
		System.out.println("반복문 끝!");
	}
	public void test2() {
		System.out.println("첫번째 정수 입력 : ");
		int num1= sc.nextInt();
		System.out.println("두번째 정수 입력 : ");
		int num2 = sc.nextInt();
		try {
			System.out.println("결과 : "+(num1/num2));
		}catch(ArithmeticException e) {
			System.out.println("0으로는 나눌 수 없습니다.");
		}
		
	}
}
